### ISSUE TITLE
[Enhancement] Add gradle build support

### ISSUE THREAD

**Issue by Ristovski** [V0idWa1k3r/ExPetrum#1]
Seeing only Eclipse is supported as a build system, it would be nice if you added Gradle build support. I might do this later if I find some time.

**Comment by V0idWa1k3r** [comment]
Yeah, I'm currently trying to make the mod functional enough. As it stans now there is no reason to build it to a jar file. I will add gradle build scripts once I feel that there are enough features

**Comment by V0idWa1k3r** [comment]
Gradle build support added as I restructured the project anyway. Feel free to play around with it, but note that you need V0idApi present in your libs folder to compile. That dependency may or may not be removed later. You also need java8 to build but that should be handled by the build script.
