### ISSUE TITLE
[1.12.2] [1.0.4] Dying while playing the anvil minigame voids armor

### ISSUE THREAD

**Issue by wamc2017** [V0idWa1k3r/ExPetrum#10]
If I play the anvil minigame while wearing some armor and use the take damage option to often it seems that the armor gets completely voided...

Also dying through wolves voids some armor pieces but not all, is this intended?

**Comment by V0idWa1k3r** [comment]
No armor pieces should be voided ever regardless of the death cause. Is the armor breaking or just dissapearing? If it's the later then I can't do much since I have no hooks into the player death method and vanilla handles both the death and drops.

**Comment by wamc2017** [comment]
It completely disappears (armor was at full health while playing the minigame)

**Comment by V0idWa1k3r** [comment]
It could still break due to a glitch with it's durability. Have you ever seen the armor damaged?

**Comment by wamc2017** [comment]
Yeah durability seems to change fine when fighting with wolves...

**Comment by wamc2017** [comment]
Ok, strange, I died while playing the minigame again, this time I weared a damaged chestplate and damaged boots, the helmet and the greaves were undamaged. After dying I found my boots and the chestplate, but both were repaired, the other two got voided...

**Comment by V0idWa1k3r** [comment]
Yeah I found out that too just now. Something is broken with the damage values as I suspected.
