### ISSUE TITLE
[1.12.2] [1.0.1] Can use bellows only one time

### ISSUE THREAD

**Issue by wamc2017** [V0idWa1k3r/ExPetrum#4]
If I place down the bellows it's only useable one time by rightclicking, I think it should be useable again after some time. Picking it up and placing it again works, don't know if this is intended...

**Comment by wamc2017** [comment]
Hmm, strange it only moves a tiny bit and is stuck on my side....

**Comment by V0idWa1k3r** [comment]
Do you have the doDaynightCycle gamerule set to false? Bellows check whether they can be clicked by remembering the last time they were clicked and if that gamerule is set to false no time passes.

**Comment by wamc2017** [comment]
doDaynightCycle is true, haven't changed any configs or gamerules...

**Comment by V0idWa1k3r** [comment]
This might be a client-side only issue. Do bellows make any noise if you click them, wait for a while and click again (do they actually work or is this a functional bug and not just a visual one)?

**Comment by wamc2017** [comment]
Yeah, the bellows makes some noise when I click it, I waited for 30 minutes, did some other stuff and clicked it again, nothing happens after the first click.

I made a video: https://www.youtube.com/watch?v=21mEBAyJTqE&feature=youtu.be

**Comment by V0idWa1k3r** [comment]
Are you able to do other things that require time to pass? Are you able to make charcoal? Do shafts powered with rotary power rotate? Does the spinning wheel spin?

**Comment by wamc2017** [comment]
Hmm, only tried charcoal so far and it worked flawlessly. Will try the wheelspin later today.

**Comment by wamc2017** [comment]
Strange, the spinning wheel seems to have the same problem and also makes some strange things after rightclicking:
![2018-07-13_18 19 44](https://user-images.githubusercontent.com/33242447/42702357-89a3273a-86c9-11e8-80b9-bd187f15c12c.png)

**Comment by V0idWa1k3r** [comment]
Oh wow those are some serious world-time desyncs. Client-side only though if you are able to make charcoal. I'll look into that.

**Comment by V0idWa1k3r** [comment]
Does your wind change direction/strength? Does the issue persist if you relog into the world and is other data(seasons/temperature/wind) properly being displayed when you relog?

**Comment by V0idWa1k3r** [comment]
Actually now thinking about it I'll just redo the whole time system of the world. The current one breaks if you do /time set literallyanything anyway.

**Comment by wamc2017** [comment]
Yeah, I used time set to make screenshots, didn't know this could be the issue... :smile:
