### ISSUE TITLE
[1.12.2] [1.0.1] Wooden crate only opens in one direction & breaks if water is placed nearby it

### ISSUE THREAD

**Issue by wamc2017** [V0idWa1k3r/ExPetrum#5]
The wooden crate only opens in one direction. Don't know if this is intended, but would be nice if it could be rotated.

If I place water in the world with a wooden bucket near a crate it breaks, could be a bit annoying...

**Comment by V0idWa1k3r** [comment]
Rotation of the crates is something I want to get done yes just didn't get to it yet. The water breaking the crates is a bug, I'll look into that.

**Comment by V0idWa1k3r** [comment]
Did the rotation on crates in 49d147fa82bb9344a1be1eb4495276cca8764335
