### ISSUE TITLE
[1.12.2] [1.0.1] Oil spawns in mid air

### ISSUE THREAD

**Issue by wamc2017** [V0idWa1k3r/ExPetrum#7]
![2018-07-13_12 42 13](https://user-images.githubusercontent.com/33242447/42687826-5925f3a0-869a-11e8-86e4-b327fe367671.png)

Oil spawns in mid air before flowing back to the ground, if this is intended, it should be maybe more rare, or it's way to easy to find oil...

**Comment by V0idWa1k3r** [comment]
That's because of fluid physics. If the fluid was a standart minecraft fluid it would stay up there and make a stream of oil. However since it is a finite liquid it falls down making a puddle. That is intended.
